# Generated by Django 4.2.11 on 2024-11-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
    ]
