# Generated by Django 4.2.11 on 2024-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(max_length=255)),
                ('expertise', models.CharField(max_length=255)),
                ('contact', models.IntegerField(null=True)),
                ('emailID', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('consulatationFee', models.IntegerField(null=True)),
            ],
        ),
    ]
