# Generated by Django 4.2.16 on 2024-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=255)),
                ('hrName', models.CharField(max_length=255)),
                ('openingDate', models.DateField(null=True)),
                ('closedDate', models.DateField(null=True)),
                ('notes', models.CharField(max_length=500)),
                ('status', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=500)),
                ('baseSalary', models.IntegerField(null=True)),
            ],
        ),
    ]
