# Generated by Django 4.2.16 on 2024-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='HiringManager',
            field=models.CharField(default='Admin', max_length=255),
            preserve_default=False,
        ),
    ]
